allow namespace to be selected with helm package type
cf-platform-eng/tile-generator pull request #278
Opened 2018-09-04 18:15 UTC by aaronmeza

Add ability to specify target PKS namespace with helm package type

- namespace can be specified in tile.yml
- removed broken pks host detection and added PKS Host form field
- Added PKS credentials to form
- Fixed allowing multiple helm chart packages to be specified in one tile

2018-09-06 18:29 UTC, keshto requested changes
I like how you are fixing other things with your PR :+1:

2018-09-06 18:29 UTC, keshto commented on tile_generator/package_definitions.py
> +        'name': {'type': 'string', 'required': True },
This property is inherited from the super class and thus is redundant.

2018-09-06 18:29 UTC, keshto commented on tile_generator/package_flags.py
> +        package['is_helm'] = True
This is an anti pattern. I know that some of the package types have this pattern but they are legacy and not desirable. One should use package_type.

2018-09-06 18:29 UTC, keshto commented on tile_generator/package_flags.py
> +                    # @todo this url no longer exists. is pks hosted publicly anywhere?
It appears that the workflow is to log into pivnet. This is not that great and we might have to host it somewhere. Maybe gitblame and ask the author for their ideas.

2018-09-06 18:29 UTC, keshto commented on tile_generator/package_flags.py
> -        if not 'pivotal-container-service' in [p['name'] for p in config_obj['requires_product_versions']]:
Why is the requirement for PKS being removed?

2018-09-06 18:29 UTC, keshto commented on tile_generator/templates/jobs/delete-charts.sh.erb
>  # FIXME - This only works for a single helm chart
Is this comment still applicable?

2018-09-06 18:29 UTC, keshto commented on tile_generator/templates/jobs/deploy-charts.sh.erb
> +{% if package.is_helm %}
use package_type

2018-09-06 18:29 UTC, keshto commented on tile_generator/templates/jobs/deploy-charts.sh.erb
> +    HELM_NAMESPACE={{ package.namespace }}
Does this handle fine when package.namespace is not defined?

2018-09-06 18:29 UTC, keshto commented on tile_generator/templates/jobs/deploy-charts.sh.erb
> +{% endfor %}
no newline at EOF :P

2018-09-06 19:22 UTC, aaronmeza commented on tile_generator/package_flags.py
> -        if not 'pivotal-container-service' in [p['name'] for p in config_obj['requires_product_versions']]:
because you don't need to install the helm chart on the local PKS host; you can install on any PKS host (or target GKE even)

2018-09-06 19:22 UTC, aaronmeza commented on tile_generator/package_flags.py
> +                    # @todo this url no longer exists. is pks hosted publicly anywhere?
taked with Mikey; going to make path an env variable

2018-09-06 19:26 UTC, aaronmeza commented on tile_generator/package_flags.py
> +        package['is_helm'] = True
will fix

2018-09-06 19:26 UTC, aaronmeza commented on tile_generator/package_definitions.py
> +        'name': {'type': 'string', 'required': True },
will fix

2018-09-06 19:30 UTC, aaronmeza commented on tile_generator/templates/jobs/delete-charts.sh.erb
>  # FIXME - This only works for a single helm chart
no. removed.

2018-09-06 19:30 UTC, aaronmeza commented on tile_generator/templates/jobs/deploy-charts.sh.erb
> +{% if package.is_helm %}
will fix

2018-10-03 18:38 UTC, keshto commented
@aaronmeza you still working on this one?

2018-10-09 17:59 UTC, keshto commented
```======================================================================
ERROR: test_helm_jobs (tile_generator.config_unittest.TestHelmType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tile_generator/config_unittest.py", line 779, in test_helm_jobs
    self.config.validate()
  File "tile_generator/config.py", line 259, in validate
    self._apply_package_flags(self, package)
  File "tile_generator/config.py", line 236, in _apply_package_flags
    flag.generate_release(config_obj, package)
  File "tile_generator/package_flags.py", line 47, in generate_release
    self._apply(config_obj, package, release)
  File "tile_generator/package_flags.py", line 331, in _apply
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_metadata_diff (tile_generator.config_unittest.TestUltimateForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/workspace/tile-generator/.venv/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "tile_generator/config_unittest.py", line 189, in test_metadata_diff
    generated_output = yaml.load(f)
NameError: global name 'yaml' is not defined

----------------------------------------------------------------------
Ran 135 tests in 5.412s

FAILED (errors=2)
```

2019-01-07 16:59 UTC, mboldt commented
This is abandoned, yes?

2019-01-07 20:33 UTC, aaronmeza commented
correct. closing.

2019-01-07 20:33 UTC, closed without merging